###
GET https://fadlisheet.herokuapp.com/api/userdata
Content-Type: application/json

{
    "token" : "jvalley2020"
}

###
POST https://fadlisheet.herokuapp.com/api/register
Content-Type: application/json

{
    "token" : "jvalley2020",
    "name" : "nonebelande",
    "email" : "nonebelande@gmail.com",
    "password" : "1qazxsw2",
    "phone" : "081213655573"
}

###
POST https://fadlisheet.herokuapp.com/api/editdata
Content-Type: application/json

{
    "token" : "jvalley2020",
    "id" : 7,
    "name" : "jonathan petrus",
    "email" : "jonathan@gmail.com",
    "password" : "1qazxsw2"
}


###
GET https://fadlisheet.herokuapp.com/api/comment
Content-Type: application/json


###
POST https://fadlisheet.herokuapp.com/api/setcomment
Content-Type: application/json

{
    "token" : "jvalley2020",
    "comment_username" : "fadliselaz",
    "comment_body" : "hallo saya test saja"
 
}

###
POST https://fadlisheet.herokuapp.com/api/login
Content-Type: application/json

{
    "token" : "jvalley2020",
    "email" : "fadliselaz@gmail.com",
    "password" : "1qazxsw2"
 
}

###
GET https://fadlisheet.herokuapp.com/api/userdata
Content-Type: application/json

{
    "token" : "jvalley2020"
}


